### PR TITLE
add input patches to buildsys

### PR DESCRIPTION
**Pull request by a1rwulf**
Add missing input patches to be fetched by the buildsystem.

### CODE REVIEW

**Comment by garbear** [comment]
looks good

**Comment by a1rwulf** [comment]
Do you want to keep any naming scheme?
I just copied them from the OE build without a rename - it was needed to start with "libretro-mupen64plus" otherwise OE won't take it...

**Comment by garbear** [comment]
i don't care about the scheme. I like 000X, because it makes it explicit what order to apply the patches when viewing the directory. if OE requires that prefix, then we best use it

**Comment by a1rwulf** [comment]
ok - I'll merge then.

**Pull request merged**
